import { Holding } from "../types";

/**
 * Static portfolio holdings — source of truth is the Excel sheet.
 * This config file contains ONLY the static identification, purchase, and sector grouping data.
 * All dynamic metrics (CMP, P/E, EPS, present values, returns) are fetched or computed live at runtime.
 */
export const holdings: Holding[] = [
  {
    id: "hdfc-bank",
    name: "HDFC Bank",
    ticker: "HDFCBANK.NS",
    googleTicker: "NSE:HDFCBANK",
    exchange: "NSE",
    exchangeCode: "HDFCBANK",
    sector: "Financial",
    domain: "hdfcbank.com",
    purchasePrice: 1490,
    quantity: 50,
  },

  {
    id: "bajaj-finance",
    name: "Bajaj Finance",
    ticker: "BAJFINANCE.NS",
    googleTicker: "NSE:BAJFINANCE",
    exchange: "NSE",
    exchangeCode: "BAJFINANCE",
    sector: "Financial",
    domain: "bajajfinserv.in",
    purchasePrice: 6466,
    quantity: 15,
  },

  {
    id: "icici-bank",
    name: "ICICI Bank",
    ticker: "ICICIBANK.NS",
    googleTicker: "NSE:ICICIBANK",
    exchange: "NSE",
    exchangeCode: "532174",
    sector: "Financial",
    domain: "icicibank.com",
    purchasePrice: 780,
    quantity: 84,
  },

  {
    id: "bajaj-housing",
    name: "Bajaj Housing Finance",
    ticker: "BAJAJHFL.NS",
    googleTicker: "NSE:BAJAJHFL",
    exchange: "NSE",
    exchangeCode: "544252",
    sector: "Financial",
    domain: "bajajhousingfinance.in",
    purchasePrice: 130,
    quantity: 504,
  },

  {
    id: "savani-financials",
    name: "Savani Financials",
    ticker: "511577.BO",
    googleTicker: "NSE:SAVANIFINL",
    exchange: "NSE",
    exchangeCode: "511577",
    sector: "Financial",
    domain: "savanifinancials.co.in",
    purchasePrice: 24,
    quantity: 1080,
  },

  {
    id: "affle-india",
    name: "Affle India",
    ticker: "AFFLE.NS",
    googleTicker: "NSE:AFFLE",
    exchange: "NSE",
    exchangeCode: "AFFLE",
    sector: "Technology",
    domain: "affle.com",
    purchasePrice: 1151,
    quantity: 50,
  },

  {
    id: "ltimindtree",
    name: "LTI Mindtree",
    ticker: "LTM.NS",
    googleTicker: "NSE:LTIM",
    exchange: "NSE",
    exchangeCode: "LTIM",
    sector: "Technology",
    domain: "ltimindtree.com",
    purchasePrice: 4775,
    quantity: 16,
  },

  {
    id: "kpit-tech",
    name: "KPIT Technologies",
    ticker: "KPITTECH.NS",
    googleTicker: "NSE:KPITTECH",
    exchange: "NSE",
    exchangeCode: "542651",
    sector: "Technology",
    domain: "kpit.com",
    purchasePrice: 672,
    quantity: 61,
  },

  {
    id: "tata-tech",
    name: "Tata Technologies",
    ticker: "TATATECH.NS",
    googleTicker: "NSE:TATATECH",
    exchange: "NSE",
    exchangeCode: "544028",
    sector: "Technology",
    domain: "tatatechnologies.com",
    purchasePrice: 1072,
    quantity: 63,
  },

  {
    id: "bls-eservices",
    name: "BLS E-Services",
    ticker: "BLSE.NS",
    googleTicker: "NSE:BLSE",
    exchange: "NSE",
    exchangeCode: "544107",
    sector: "Technology",
    domain: "blseservices.com",
    purchasePrice: 232,
    quantity: 191,
  },

  {
    id: "tanla-platforms",
    name: "Tanla Platforms",
    ticker: "TANLA.NS",
    googleTicker: "NSE:TANLA",
    exchange: "NSE",
    exchangeCode: "532790",
    sector: "Technology",
    domain: "tanla.com",
    purchasePrice: 1134,
    quantity: 45,
  },

  {
    id: "dmart",
    name: "DMart (Avenue Supermarts)",
    ticker: "DMART.NS",
    googleTicker: "NSE:DMART",
    exchange: "NSE",
    exchangeCode: "DMART",
    sector: "Consumer",
    domain: "dmartindia.com",
    purchasePrice: 3777,
    quantity: 27,
  },

  {
    id: "tata-consumer",
    name: "Tata Consumer Products",
    ticker: "TATACONSUM.NS",
    googleTicker: "NSE:TATACONSUM",
    exchange: "NSE",
    exchangeCode: "532540",
    sector: "Consumer",
    domain: "tataconsumer.com",
    purchasePrice: 845,
    quantity: 90,
  },

  {
    id: "pidilite",
    name: "Pidilite Industries",
    ticker: "PIDILITIND.NS",
    googleTicker: "NSE:PIDILITIND",
    exchange: "NSE",
    exchangeCode: "500331",
    sector: "Consumer",
    domain: "pidilite.com",
    purchasePrice: 2376,
    quantity: 36,
  },

  {
    id: "tata-power",
    name: "Tata Power",
    ticker: "TATAPOWER.NS",
    googleTicker: "NSE:TATAPOWER",
    exchange: "NSE",
    exchangeCode: "500400",
    sector: "Power",
    domain: "tatapower.com",
    purchasePrice: 224,
    quantity: 225,
  },

  {
    id: "kpi-green",
    name: "KPI Green Energy",
    ticker: "KPIGREEN.NS",
    googleTicker: "NSE:KPIGREEN",
    exchange: "NSE",
    exchangeCode: "542323",
    sector: "Power",
    domain: "kpigreenenergy.com",
    purchasePrice: 875,
    quantity: 50,
  },

  {
    id: "suzlon",
    name: "Suzlon Energy",
    ticker: "SUZLON.NS",
    googleTicker: "NSE:SUZLON",
    exchange: "NSE",
    exchangeCode: "532667",
    sector: "Power",
    domain: "suzlon.com",
    purchasePrice: 44,
    quantity: 450,
  },

  {
    id: "gensol",
    name: "Gensol Engineering",
    ticker: "GENSOL.NS",
    googleTicker: "NSE:GENSOL",
    exchange: "NSE",
    exchangeCode: "542851",
    sector: "Power",
    domain: "gensol.in",
    purchasePrice: 998,
    quantity: 45,
  },

  {
    id: "hariom-pipes",
    name: "Hariom Pipe Industries",
    ticker: "HARIOMPIPE.NS",
    googleTicker: "NSE:HARIOMPIPE",
    exchange: "NSE",
    exchangeCode: "543517",
    sector: "Pipes",
    domain: "hariompipes.com",
    purchasePrice: 580,
    quantity: 60,
  },

  {
    id: "astral",
    name: "Astral Ltd",
    ticker: "ASTRAL.NS",
    googleTicker: "NSE:ASTRAL",
    exchange: "NSE",
    exchangeCode: "ASTRAL",
    sector: "Pipes",
    domain: "astralpipes.com",
    purchasePrice: 1517,
    quantity: 56,
  },

  {
    id: "polycab",
    name: "Polycab India",
    ticker: "POLYCAB.NS",
    googleTicker: "NSE:POLYCAB",
    exchange: "NSE",
    exchangeCode: "542652",
    sector: "Pipes",
    domain: "polycab.com",
    purchasePrice: 2818,
    quantity: 28,
  },

  {
    id: "clean-science",
    name: "Clean Science & Technology",
    ticker: "CLEAN.NS",
    googleTicker: "NSE:CLEAN",
    exchange: "NSE",
    exchangeCode: "543318",
    sector: "Specialty Chemicals",
    domain: "cleanscience.co.in",
    purchasePrice: 1610,
    quantity: 32,
  },

  {
    id: "deepak-nitrite",
    name: "Deepak Nitrite",
    ticker: "DEEPAKNTR.NS",
    googleTicker: "NSE:DEEPAKNTR",
    exchange: "NSE",
    exchangeCode: "506401",
    sector: "Specialty Chemicals",
    domain: "godeepak.com",
    purchasePrice: 2248,
    quantity: 27,
  },

  {
    id: "fine-organic",
    name: "Fine Organic Industries",
    ticker: "FINEORG.NS",
    googleTicker: "NSE:FINEORG",
    exchange: "NSE",
    exchangeCode: "541557",
    sector: "Specialty Chemicals",
    domain: "fineorganics.com",
    purchasePrice: 4284,
    quantity: 16,
  },

  {
    id: "gravita",
    name: "Gravita India",
    ticker: "GRAVITA.NS",
    googleTicker: "NSE:GRAVITA",
    exchange: "NSE",
    exchangeCode: "533282",
    sector: "Others",
    domain: "gravitaindia.com",
    purchasePrice: 2037,
    quantity: 8,
  },

  {
    id: "sbi-life",
    name: "SBI Life Insurance",
    ticker: "SBILIFE.NS",
    googleTicker: "NSE:SBILIFE",
    exchange: "NSE",
    exchangeCode: "540719",
    sector: "Others",
    domain: "sbilife.co.in",
    purchasePrice: 1197,
    quantity: 49,
  },

  {
    id: "infy",
    name: "Infosys",
    ticker: "INFY.NS",
    googleTicker: "NSE:INFY",
    exchange: "NSE",
    exchangeCode: "500209",
    sector: "Others",
    domain: "infosys.com",
    purchasePrice: 1647,
    quantity: 36,
  },

  {
    id: "happiest-minds",
    name: "Happiest Minds",
    ticker: "HAPPSTMNDS.NS",
    googleTicker: "NSE:HAPPIESTMIN",
    exchange: "NSE",
    exchangeCode: "543237",
    sector: "Others",
    domain: "happiestminds.com",
    purchasePrice: 1103,
    quantity: 45,
  },

  {
    id: "easemytrip",
    name: "EaseMyTrip",
    ticker: "EASEMYTRIP.NS",
    googleTicker: "NSE:EASEMYTRIP",
    exchange: "NSE",
    exchangeCode: "543272",
    sector: "Others",
    domain: "easemytrip.com",
    purchasePrice: 20,
    quantity: 1332,
  },

];

export const SECTORS = [...new Set(holdings.map((h) => h.sector))];
export const ALL_TICKERS = holdings.map((h) => h.ticker);
export const ALL_GOOGLE_TICKERS = holdings.map((h) => h.googleTicker);
export const TOTAL_COST_BASIS = holdings.reduce(
  (sum, h) => sum + h.purchasePrice * h.quantity,
  0
);
